
worker_processes 1;

events { worker_connections 1024; }

http {
    server_names_hash_bucket_size 128;
    server {
        listen 80;
        server_name mechanochemistry-db-01-dev.chem.tamu.edu;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://host.containers.internal:85;
        }
    }
    server {
        listen 80;
        server_name mechanochemistry.chem.tamu.edu;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://host.containers.internal:85;
        }
    }
    server {
        listen 80;
        server_name preview-mechanochemistry-db-01-dev.chem.tamu.edu;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://host.containers.internal:90;
        }
    }
    server {
        listen 80;
        server_name preview-mechanochemistry.chem.tamu.edu;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://host.containers.internal:90;
        }
    }
    server {
        listen 8070;
        server_name preview-mechanochemistry.chem.tamu.edu;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://host.containers.internal:91;
        }
    }
}
