name: "Indole_Synthesis"
description: "Indole_Synthesis"
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "IndoleSynthesis"
  }
  inputs {
    key: "Ethyl Acrylates"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C=CC(OCC)=O"
        }
        amount {
          moles {
            value: 1.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      addition_order: 1
    }
  }
  inputs {
    key: "N-methylIndoles"
    value {
      components {
        identifiers {
          type: SMILES
          value: "CN1C2=CC=CC=C2C=C1"
        }
        amount {
          moles {
            value: 1.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        preparations {
          type: CUSTOM
          details: "A solution of dimers in DMSO (100 \316\274L, 0.3 mM) was prepared\n"
        }
      }
      addition_order: 2
    }
  }
  setup {
    vessel {
      type: CUSTOM
      details: "Ball" 
      material {
        type: METAL
        details: "Ball Mills"
      }
      volume {
        value: 2.0
        units: MILLILITER
      }
    }
  }
  conditions {
    temperature {
      setpoint {
        value: 25.0
        units: CELSIUS
      }
    }
    stirring {
      type: BALL_MILLING
    }
  }
  notes {
    procedure_details: ""
  }
  outcomes {
    reaction_time {
      value: 0.417
      units: HOUR
    }
    conversion {
      value: 99.99
    }
    products {
      identifiers {
        type: SMILES
        value: "CN1C=C(/C=C/C(OCC)=O)C2=C1C=CC=C2"
      }
    }
    analyses {
      key: "NMR_1H"
      value {
        type: CUSTOM
        details: "NMR"
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0000-0000-0000"
      organization: "Department of Chemistry, TAMU "
    }
    city: "College Station"
    doi: "10.1021/acs.joc.6b01138"
    publication_url: "https://pubs.acs.org/doi/10.1021/acs.joc.6b01138#"
    record_created {
      time {
        value: "6/4/2024, 10:53 AM"
      }
      person {
        name: "THC"
        orcid: "0000-0000-0000-0000"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
  reaction_id: "ord-b36d7b14db744cd291c48bdbcf364b14"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "IndoleSynthesis"
  }
  inputs {
    key: "Ethyl Acrylates"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C=CC(OCC)=O"
        }
        amount {
          moles {
            value: 1.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      addition_order: 1
    }
  }
  inputs {
    key: "N-methylIndoles"
    value {
      components {
        identifiers {
          type: SMILES
          value: "CN1C2=CC=CC=C2C=C1"
        }
        amount {
          moles {
            value: 1.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        preparations {
          type: CUSTOM
          details: "A solution of dimers in DMSO (100 \316\274L, 0.3 mM) was prepared\n"
        }
      }
      addition_order: 2
    }
  }
  setup {
    vessel {
      type: VIAL
      material {
        type: GLASS
        details: "Ball Mills"
      }
      volume {
        value: 2.0
        units: MILLILITER
      }
    }
  }
  conditions {
    pressure {
      control {
        type: SEALED
        details: "Ball Mills"
      }
    }
  }
  outcomes {
    reaction_time {
      value: 48.0
      units: HOUR
    }
    conversion {
      value: 99.99
    }
    products {
      identifiers {
        type: SMILES
        value: "CN1C=C(/C=C/C(OCC)=O)C2=C1C=CC=C2"
      }
    }
    analyses {
      key: "NMR_1H"
      value {
        type: CUSTOM
        details: "NMR"
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0000-0000-0000"
      organization: "Department of Chemistry, TAMU "
    }
    city: "College Station"
    doi: "10.1021/acs.joc.6b01138"
    publication_url: "https://pubs.acs.org/doi/10.1021/acs.joc.6b01138#"
    record_created {
      time {
        value: "6/4/2024, 10:53 AM"
      }
      person {
        name: "THC"
        orcid: "0000-0000-0000-0000"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
  reaction_id: "ord-b36d7b14db744cd291c48bdbcf364b14"
}
dataset_id: "ord_dataset-f388f8c73d6343189093770060fc3097"
