const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { createRequire } = require('node:module')
const appRequire = createRequire(path.resolve(__dirname, '../package.json'))
const babel = appRequire('@babel/core')
const cache = {}
function loadUtility(name) {
  if (cache[name]) return cache[name]
  const filename = path.resolve(__dirname, `../src/utils/${name}.js`)
  const { code } = babel.transformSync(fs.readFileSync(filename, 'utf8'), {
    filename, babelrc: false, configFile: false,
    plugins: [appRequire.resolve('@babel/plugin-transform-modules-commonjs')],
  })
  const module = { exports: {} }
  new Function('require', 'module', 'exports', code)(
    id => id.startsWith('./') ? loadUtility(id.slice(2)) : appRequire(id), module, module.exports)
  return cache[name] = module.exports
}
const { conditionRows, availableConditions } = loadUtility('conditionDisplay')
const { collectAuxiliaryData, dataPresentation, resolveDataUrl } = loadUtility('auxiliaryData')
const pb = appRequire('cmccdb-schema')

// Use the same serialized protobuf objects consumed by the reaction page.
const conditions = new pb.ReactionConditions()
conditions.setPh(0).setReflux(false).setConditionsAreDynamic(false)
conditions.setTemperature(new pb.TemperatureConditions().setSetpoint(new pb.Temperature().setValue(0).setUnits(1)))
conditions.setMechanochemistry(new pb.MechanochemistryConditions().setType(3)
  .setFrequency(new pb.Frequency().setValue(18).setPrecision(0).setUnits(1))
  .setDuration(new pb.Time().setValue(72000).setUnits(3))
  .setBallMaterial('Stainless Steel').setCellMaterial('Stainless Steel')
  .setDimensionList([new pb.Length().setValue(0).setUnits(2), new pb.Length().setValue(5).setUnits(2)]))
const value = pb.ReactionConditions.deserializeBinary(conditions.serializeBinary()).toObject()
assert.deepEqual(availableConditions(value), ['temperature', 'mechanochemistry', 'other'])
assert.deepEqual(conditionRows(value, 'other'), [
  { label: 'Reflux', value: 'No' }, { label: 'pH', value: '0' },
  { label: 'Conditions are dynamic', value: 'No' },
])
const rows = conditionRows(value, 'mechanochemistry')
assert(rows.some(row => row.label === 'Type' && row.value === 'Ball mill'))
assert(rows.some(row => row.label === 'Frequency' && row.value === '18 ± 0 Hz'))
assert(rows.some(row => row.label === 'Duration' && row.value === '72000 s'))
assert(rows.some(row => row.label === 'Ball material' && row.value === 'Stainless Steel'))
assert(rows.some(row => row.label === 'Dimension 1' && row.value === '0 mm'))
assert(rows.some(row => row.label === 'Dimension 2' && row.value === '5 mm'))
assert(conditionRows(value, 'temperature').some(row => row.value === '0 °C'))
assert.equal(conditionRows({ temperature: { setpoint: { value: 273.15, units: 3 } } }, 'temperature')[0].value, '273.15 K')
assert.equal(conditionRows({ illumination: { peakWavelength: { value: 450, units: 1 } } }, 'illumination')[0].value, '450 nm')
assert.deepEqual(conditionRows({ pressure: {} }, 'pressure'), [])
assert.deepEqual(availableConditions(), [])
assert.equal(conditionRows({ flow: { type: 999 } }, 'flow')[0].value, '999')

const reaction = new pb.Reaction()
reaction.setConditions(conditions)
const input = new pb.ReactionInput()
const compound = new pb.Compound()
compound.getFeaturesMap().set('Input feature', new pb.Data().setStringValue('Feature text'))
input.addComponents(compound)
reaction.getInputsMap().set('Sample input', input)
const setup = new pb.ReactionSetup()
setup.getAutomationCodeMap().set('Procedure', new pb.Data().setUrl('procedure.py'))
reaction.setSetup(setup)
const outcome = new pb.ReactionOutcome()
const analysis = new pb.Analysis()
analysis.getDataMap().set('Spectrum', new pb.Data().setUrl('spectrum.PNG?version=1').setDescription('Measured spectrum'))
analysis.getDataMap().set('Raw data', new pb.Data().setUrl('spectrum.csv'))
outcome.getAnalysesMap().set('XAS', analysis)
const product = new pb.ProductCompound()
product.getFeaturesMap().set('Count', new pb.Data().setIntegerValue(0))
outcome.addProducts(product)
reaction.addOutcomes(outcome)
reaction.addObservations(new pb.ReactionObservation().setImage(new pb.Data().setBytesValue('aGVsbG8=').setFormat('image/png')))
const provenance = new pb.ReactionProvenance()
provenance.getReactionMetadataMap().set('Note', new pb.Data().setStringValue('<script>alert(1)</script>'))
reaction.setProvenance(provenance)
const serialized = pb.Reaction.deserializeBinary(reaction.serializeBinary()).toObject()
const entries = collectAuxiliaryData(serialized)
assert.equal(entries.length, 7)
const spectrum = entries.find(entry => entry.label === 'Spectrum')
assert.equal(spectrum.context, 'Outcomes 1 / Analyses / XAS / Data')
const presentation = dataPresentation(spectrum, 'cmcc-test', 'staging')
assert.equal(presentation.isImage, true)
assert(presentation.href.startsWith('/api/auxiliary/cmcc-test?'))
assert.equal(new URL(presentation.href, 'http://localhost').searchParams.get('url'), 'spectrum.PNG?version=1')
assert.equal(new URL(presentation.href, 'http://localhost').searchParams.get('database'), 'staging')
assert.equal(dataPresentation(entries.find(entry => entry.label === 'Count'), 'cmcc-test').value, 0)
assert.equal(dataPresentation(entries.find(entry => entry.label === 'Image'), 'cmcc-test').href, 'data:image/png;base64,aGVsbG8=')
assert.equal(resolveDataUrl('https://example.org/plot.svg', 'cmcc-test'), 'https://example.org/plot.svg')
assert.equal(resolveDataUrl('javascript:alert(1)', 'cmcc-test'), '')
assert.equal(resolveDataUrl('file:///private/file.png', 'cmcc-test'), '')
assert.equal(resolveDataUrl('java\nscript:alert(1)', 'cmcc-test'), '')
console.log('Reaction display checks passed: protobuf round trips, every Data source, units, zeros, repeated values and file links.')
