name: CI

on:
 push:
   branches: 
     - master
 pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.0
    - name: Run protoc
      run: |
        cd "${GITHUB_WORKSPACE}/proto"
        mkdir python
        protoc ord_schema.proto --python_out=python
